import Head from 'next/head'
import React from 'react'

const About = () => {
    return (
        <div className="container">
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className='main'>
                <h1>About</h1>
            </main>

        </div>
    )
}

export default About